services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DB_ROOT}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql


  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    image: nginx:inception
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lpires-n/data/wordpress

  mariadb_data:
    name: mariadb-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lpires-n/data/mariadb
