services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env


networks:
  inception:
    driver: bridge
