services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    healthcheck:
      test: /usr/bin/mariadb-admin ping -h localhost
      interval: 30s
      timeout: 10s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

networks:
  inception:
    driver: bridge
