services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    healthcheck:
      test: mysqladmin  ping -h localhost
      interval: 30s
      timeout: 10s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
